name: Tweet Daily Air Quality

on:
  schedule:
    # Run at 8:00 AM IST (which is 2:30 AM UTC)
    - cron: '30 2 * * *'
  # Optional: Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  tweet-aqi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create .env file
        run: |
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" > .env
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> .env
          echo "OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: Run bot
        run: python aqi_bot.py